export const ENV = {
  SERVER_HOST: "http://127.0.0.1:1337",
  API_URL: "http://127.0.0.1:1337/api",
  ENDPOINTS: {
    AUTH: {
      REGISTER: "auth/local/register",
      LOGIN: "auth/local",
    },
    USERS_ME: "users/me",
    USERS: "users",
    ADDRESS: "addresses",
    MAINMENU: "main-menus",
    PLATFORM: "platforms",
    GAME: "games",
    WISHLIST: "wishlists",
    POST: "posts",
    CATEGORY_POST: "category-posts",
    PROJECT: "proyects",
    CATEGORY_PROJECT: "category-proyects",
    PRODUCT: "products",
    CATEGORY_PRODUCT: "category-products",
    PRODUCT_WISHLIST: "products-wishlists",
    REQUISITION: "onrequests",
    CATEGORY_REQUISITION: "category-onrequests",
    REQUISITION_BUDGET: "budgets",
    PAYMENY_ORDER: "payment-order",
    ORDER: "orders",
  },
  TOKEN: "token",
  CART: "cart",
  STRIPE_TOKEN: "",
};
